### ISSUE TITLE
Multi Mod Management

### ISSUE THREAD

**Issue by niheaven** [ppkantorski/Mod-Alchemist#2]
If I have multiple mods that may modify same files, and try to toggle all of them on, then what's the sequence? Could I toggle them one by one, and if I deactivate one mod, will the remaining active mods continue to function?

**Comment by ppkantorski** [comment]
Im assuming you are referring to content mods.  Duplicate files are handled properly, yes.

**Comment by niheaven** [comment]
Do I need to activate each one individually and then deactivate FILO, or can it be done in any order?

**Comment by ppkantorski** [comment]
any order.  duplicate files are handled accordingly.  however this assumes you are managing all content mods for the game from Mod Alchemist

**Comment by niheaven** [comment]
And for the final question, if I have a cheats file in `atmosphere/contents`, it should remain unaffected during the activation and deactivation of mods, correct?

**Comment by ppkantorski** [comment]
> And for the final question, if I have a cheats file in `atmosphere/contents`, it should remain unaffected during the activation and deactivation of mods, correct?

yeah exefs patches and cheats are separate.  while some *might* interfere with one another, they are ran / loaded separate from one another.
